---
- name: Set up environment 
  hosts: localhost
  become: true

  tasks:
    - name: Install needed apt packages
      ansible.builtin.apt:
        pkg:
          - git
          - moreutils
          - build-essential
          - curl
          - python3
          - python3-pip
          - python3-venv
        update_cache: true

    - name: Download and install xan
      ansible.builtin.shell: |
        curl -L https://github.com/medialab/xan/releases/download/0.57.0/xan-x86_64-unknown-linux-gnu.tar.gz | tar -xvz
        mv xan /usr/local/bin/xan
        chmod +x /usr/local/bin/xan
      args:
        creates: /usr/local/bin/xan

    - name: Install python3 dependencies
      ansible.builtin.pip: 
        requirements: /usr/local/wals_analysis/requirements.txt
        virtualenv: /usr/local/wals_analysis/.venv
        virtualenv_command: python3 -m venv
